subinclude("//test/export:export_e2e_test_build_def")

# Test multiple targets.
please_export_e2e_test(
    name = "export_multiple_targets",
    export_targets = [
        "//:target1",
        "//:target2",
    ],
)
