go_binary(
    name = "build_langserver",
    srcs = ["build_langserver.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/cli",
        "//third_party/go:logging",
        "//tools/build_langserver/lsp",
        "//tools/build_langserver/langserver",
    ],

)