python_test(
    name = "isolated_custom_runner_test",
    srcs = ["custom_runner_test.py"],
    test_runner = "test.python_rules.custom_runner.runner.run",
    deps = [
        "//test/python_rules/custom_runner:runner",
    ],
)
