go_library(
    name = "plz",
    srcs = ["plz.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/build",
        "//src/cli",
        "//src/core",
        "//src/fs",
        "//src/lint",
        "//src/metrics",
        "//src/parse",
        "//src/remote",
        "//src/test",
        "//third_party/go:logging",
    ],
)
