subinclude("//test/export:export_e2e_test_build_def")

# Test go_test target with a go third_party dependency that implicitly requires other packages.
please_export_e2e_test(
    name = "export_go_test",
    export_targets = ["//:test"],
)
