go_binary(
    name = "plugin_config_tool",
    srcs = ["plugin_config_tool.go"],
    deps = [
        "///third_party/go/github.com_peterebden_go-cli-init_v5//flags",
        "///third_party/go/github.com_please-build_gcfg//:gcfg",
        "//src/core",
        "//docs/tools/lexicon_templater/rules:rules",
        "//docs/tools/plugin_config_tool/plugin",
    ],
    visibility = ["//docs/..."],
)