go_binary(
    name = "plugin_config_tool",
    srcs = ["plugin_config_tool.go"],
    deps = [
        "//third_party/go:cli-init",
        "//third_party/go:gcfg",
        "//src/core",
        "//docs/tools/lexicon_templater/rules:rules",
        "//docs/tools/plugin_config_tool/plugin",
    ],
    visibility = ["//docs/..."],
)