freebsd_instance:
  image_family: freebsd-12-1

env:
  GOPROXY: https://proxy.golang.org

task:
  install_script: pkg install -y bash protobuf go git python3 && python3 -m ensurepip
  build_script: ./bootstrap.sh --exclude pip --exclude py2 --exclude no_cirrus
  always:
    log_artifacts:
      path: plz-out/log/*.log
      type: text/plain
    test_artifacts:
      path: plz-out/log/test_results.xml
      type: text/xml
      format: junit
