freebsd_instance:
  image: freebsd-11-2-release-amd64

env:
  GOPROXY: https://proxy.golang.org

task:
  install_script: pkg install -y bash protobuf go git python3 && python3 -m ensurepip
  bashrc_script: touch ~/.bashrc
  build_script: PLZ_ARGS="-o cache.httpurl:http://$CIRRUS_HTTP_CACHE_HOST" ./bootstrap.sh --exclude pip --exclude py2 --exclude no_cirrus
