freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  install_script: pkg install -y bash protobuf go git python3
  build_script: ./bootstrap.sh --exclude pip --exclude py2 --exclude no_cirrus
