freebsd_instance:
  image_family: freebsd-14-2

env:
  GOPROXY: https://proxy.golang.org

task:
  install_script:
    "pkg install -y bash protobuf go124 git python3 && python3 -m ensurepip && ln -s `command -v go124` /usr/local/bin/go"
  build_script: ./bootstrap.sh --exclude pip --exclude py2 --exclude=py3 --exclude=python3 --exclude no_cirrus
  always:
    log_artifacts:
      path: plz-out/log/*.log
      type: text/plain
    test_artifacts:
      path: plz-out/log/test_results.xml
      type: text/xml
      format: junit
