run:
  timeout: 5m
  skip-dirs:
    - test_data

issues:
  exclude:
    - SA4006  # Too many false positives :(
    - SA5008  # Warns for duplicate struct tags which are meaningful to go-flags
    - unslice  # This may be useful in some places.
    - ifElseChain  # Generally don't agree.
    - appendAssign
    - halp  # Make misspell be quiet about this.
    - exitAfterDefer # Potentially useful but not in any cases it fires right now.
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
    - path: src/core/config.go # The config struct is big & complex and there's usually only one.
      text: fieldalignment
      linters:
        - govet
    - path: src/please.go # Similarly for flags.
      text: fieldalignment
      linters:
        - govet

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - exportloopref
    - gci
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - tenv
    - thelper
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace

    # To consider enabling in future (once we fix errors etc):
    # - errcheck
    # - scopelint

linters-settings:
  govet:
    enable-all: true
    disable:
      - deepequalerrors # Only seen this once and it's a false positive
      - shadow # Probably not useful enough to clean everything up
      # TODO(peterebden): Should clean up these warnings & enable (although they are pretty finicky)
      - fieldalignment
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/thought-machine/please)
