go_test(
    name = "double_path_import_test",
    srcs = ["double_path_import_test.go"],
    deps = [
        "//test/go_rules/double_path_import/bar/bar:baz",
        "//test/go_rules/double_path_import/foo/foo",
    ],
)
