filegroup(
    name = "inner",
    srcs = ["inner.build_defs"],
    visibility = ["//test/revdeps/..."],
)

filegroup(
    name = "outer",
    srcs = ["outer.build_defs"],
    visibility = ["//test/revdeps/..."],
)
