go_binary(
    name = "asp",
    srcs = ["main.go"],
    deps = [
        "//rules",
        "//src/cli",
        "//src/cli/logging",
        "//src/core",
        "//src/parse/asp",
        "//third_party/go:spew",
    ],
)
