go_library(
    name = "export",
    srcs = ["export.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/core",
        "//src/fs",
        "//src/gc",
        "//src/parse",
        "//third_party/go:logging",
    ],
)
