package export

import (
	"path/filepath"

	"github.com/thought-machine/please/src/core"
	"github.com/thought-machine/please/src/fs"
	"github.com/thought-machine/please/src/parse"
)

// noTrimExporter implements an exporter that avoids trimming any packages by exporting all targets
// and statements in a package.
type noTrimExporter struct {
	*baseExporter
	// exportedPackages tracks which packages have already had their BUILD files exported.
	exportedPackages map[string]bool
}

func (nte *noTrimExporter) ExportPreloaded() {
	// Write any preloaded build defs
	for _, preload := range nte.state.Config.Parse.PreloadBuildDefs {
		if err := fs.RecursiveCopy(preload, filepath.Join(nte.targetDir, preload), 0); err != nil {
			log.Errorf("Failed to copy preloaded build def %s: %s", preload, err)
		}
	}

	for _, target := range nte.state.Config.Parse.PreloadSubincludes {
		targets := append(nte.state.Graph.TransitiveSubincludes(target), target)
		nte.exportTargets(targets)
	}
}

func (nte *noTrimExporter) ExportTarget(target *core.BuildTarget) {
	pkg := nte.state.Graph.PackageOrDie(target.Label)
	if !nte.checkAndSetVisited(target) {
		return
	}

	// We want to export the package that made this subrepo available, but we still need to walk the target deps
	// as it may depend on other subrepos or first party targets
	if target.Subrepo != nil {
		nte.ExportTarget(target.Subrepo.Target)
		nte.exportDependencies(target)
		return
	}

	nte.exportPackage(pkg)
	nte.exportSubincludes(pkg)
	nte.exportAllTargets(pkg)
	nte.exportSources(target)
	nte.exportDependencies(target)
}

func (nte *noTrimExporter) WritePackageFiles() {
}

// exportPackage exports the package BUILD file.
func (nte *noTrimExporter) exportPackage(pkg *core.Package) {
	// Skip subrepos and internal packages. These will be generated by build statements in the exported
	// repo or included in please internally.
	if pkg.Subrepo != nil || pkg.Name == parse.InternalPackageName {
		return
	}

	if nte.exportedPackages[pkg.Name] {
		return
	}
	nte.exportedPackages[pkg.Name] = true

	exportedFilename := filepath.Join(nte.targetDir, pkg.Filename)
	if err := fs.CopyFile(pkg.Filename, exportedFilename, 0); err != nil {
		log.Errorf("failed to export package %s: %v", pkg.Name, err)
	}
}

// exportSubincludes exports the subincluded targets.
func (nte *noTrimExporter) exportSubincludes(pkg *core.Package) {
	subincludes := pkg.AllSubincludes(nte.state.Graph)
	nte.exportTargets(subincludes)
}

// exportAllTargets will export all the targets in the provided package.
func (nte *noTrimExporter) exportAllTargets(pkg *core.Package) {
	for _, target := range pkg.AllTargets() {
		nte.ExportTarget(target)
	}
}
