package export

import (
	"path/filepath"

	"github.com/thought-machine/please/src/core"
	"github.com/thought-machine/please/src/fs"
	"github.com/thought-machine/please/src/parse"
)

// noTrimExporter implements an exporter that avoids trimming any packages by exporting all targets
// and statements in a package.
type noTrimExporter struct {
	*baseExporter
	// exportedPackages tracks which packages have already had their BUILD files exported.
	exportedPackages map[core.BuildLabel]bool
}

func newNoTrimExporter(base *baseExporter) exporterImpl {
	return &noTrimExporter{
		baseExporter:     base,
		exportedPackages: map[core.BuildLabel]bool{},
	}
}

// exportPreloaded implements [exporterImpl].
func (nte *noTrimExporter) exportPreloaded() {
	// Write any preloaded build defs
	for _, preload := range nte.state.Config.Parse.PreloadBuildDefs {
		if err := fs.RecursiveCopy(preload, filepath.Join(nte.targetDir, preload), 0); err != nil {
			log.Errorf("Failed to copy preloaded build def %s: %s", preload, err)
		}
	}

	for _, target := range nte.state.Config.Parse.PreloadSubincludes {
		targets := append(nte.state.Graph.TransitiveSubincludes(target), target)
		nte.exportTargets(targets)
	}
}

// exportTarget implements [exporterImpl].
func (nte *noTrimExporter) exportTarget(target *core.BuildTarget) {
	pkg := nte.getOrParsePackage(target.Label)
	if pkg == nil {
		log.Errorf("Unable to lookup package %s", target.Label)
		return
	}

	if !nte.checkAndSetVisited(target) {
		return
	}

	// We want to export the package that made this subrepo available, but we still need to walk the target deps
	// as it may depend on other subrepos or first party targets
	if target.Subrepo != nil {
		nte.exportTarget(target.Subrepo.Target)
		nte.exportDependencies(target)
		return
	}

	nte.exportSubincludes(pkg)
	nte.exportPackage(pkg)
	nte.exportSources(target)
	nte.exportDependencies(target)
}

// writePackageFiles implements [exporterImpl].
func (nte *noTrimExporter) writePackageFiles() {
	for pkgLabel := range nte.exportedPackages {
		pkg := nte.getOrParsePackage(pkgLabel)
		if pkg == nil {
			log.Errorf("Unable to lookup package %s", pkgLabel)
			continue
		}

		exportedFilename := filepath.Join(nte.targetDir, pkg.Filename)
		if err := fs.CopyFile(pkg.Filename, exportedFilename, 0); err != nil {
			log.Errorf("failed to export package %s: %v", pkg.Name, err)
		}
	}
}

// exportPackage exports the package BUILD file.
func (nte *noTrimExporter) exportPackage(pkg *core.Package) {
	// Skip subrepos and internal packages. These will be generated by build statements in the exported
	// repo or included in please internally.
	if pkg.Subrepo != nil || pkg.Name == parse.InternalPackageName {
		return
	}

	if nte.exportedPackages[pkg.Label()] {
		return
	}
	nte.exportedPackages[pkg.Label()] = true

	// Export all the targets in the provided package.
	for _, target := range pkg.AllTargets() {
		nte.exportTarget(target)
	}
}

// exportSubincludes exports the subincluded targets.
func (nte *noTrimExporter) exportSubincludes(pkg *core.Package) {
	subincludes := pkg.AllSubincludes(nte.state.Graph)
	nte.exportTargets(subincludes)
}
