subinclude("//test/export:export_e2e_test_build_def")

# Test go target with go third_party dependency.
please_export_e2e_test(
    name = "export_go_target",
    export_targets = ["//:bin_go_dep"],
)
