go_binary(
    name = "please_wrapper",
    srcs = ["main.go"],
    deps = [
        "//src/cli",
        "//src/core",
        "//src/fs",
        "//src/update",
        "//third_party/go:logging",
    ],
)
