go_binary(
    name = "please_go_test",
    srcs = ["plz_go_test.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/cli",
        "//third_party/go:logging",
        "//tools/please_go_test/gotest",
    ],
)
