go_library(
    name = "ar",
    srcs = ["ar.go"],
    visibility = ["//tools/jarcat/..."],
    deps = [
        "//src/fs",
        "//third_party/go:ar",
        "//third_party/go:logging",
    ],
)
