# This contains an arbitrary set of rules intended to exercise
# aspects of the cross-compilation code.

go_library(
    name = "lib",
    srcs = ["lib.go"],
    visibility = ["//test/cross_compile:all"],
)
