go_library(
    name = "debug",
    srcs = ["debug.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/cli/logging",
        "//src/core",
        "//src/exec",
        "//src/process",
    ],
)
