filegroup(
    name = "plz_e2e_test",
    srcs = ["example.build_defs"],
    visibility = ["PUBLIC"],
)

randoms = [
    "//src/core",
    "//src/fs",
    "//src/parse",
    "//src/parse/asp",
    "//rules",
    "//third_party/go:jsonrpc2",
    "//third_party/go:logging",
    "//tools/build_langserver/lsp",
]
