go_binary(
    name = "http_cache",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/cli",
        "//third_party/go:logging",
        "//tools/http_cache/cache",
    ],
)
