go_binary(
    name = "compiler",
    srcs = ["compiler.go"],
    visibility = ["//rules:all"],
    deps = [
        "//src/cli",
        "//src/core",
        "//src/parse/asp",
        "//third_party/go:logging",
    ],
)
