go_library(
    name = "generate",
    srcs = ["generate.go"],
    visibility = ["//src/..."],
    deps = [
        "//src/core",
        "//src/fs",
        "//src/scm",
        "//third_party/go:logging",
    ],
)
