go_library(
    name = "generate",
    srcs = ["generate.go"],
    pgo_file = "//:pgo",
    visibility = ["//src/..."],
    deps = [
        "//src/cli/logging",
        "//src/core",
        "//src/fs",
        "//src/scm",
    ],
)
