go_library(
    name = "worker",
    srcs = [
        "types.go",
        "worker.go",
    ],
    visibility = ["//src/..."],
    deps = [
        "//src/cli/logging",
        "//src/core",
        "//src/process",
    ],
)
