go_library(
    name = "worker",
    srcs = [
        "types.go",
        "worker.go",
    ],
    visibility = ["//src/..."],
    deps = [
        "//src/core",
        "//src/process",
        "//third_party/go:logging",
    ],
)
