python_library(
    name = "runner",
    srcs = ["runner.py"],
    deps = [
        "//third_party/python:coverage",
        "//third_party/python:pytest",
    ],
    visibility = ["//test/python_rules/custom_runner/..."]
)
