# Not an automated test as this package takes a very long time to compile
# TODO(jpoole): find a smaller lib to test pkg-config
go_binary(
    name="gotk3_test",
    srcs = ["main.go"],
    deps = ["//third_party/go:gotk3"],
)

