plugin_repo(
    name = "go",
    plugin = "go-rules",
    revision = "f8b41f02617dccad23fb10487bebc9feea538c09",
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)

plugin_repo(
    name = "java",
    plugin = "java-rules",
    revision = "v0.2.4",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.1.1",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    # TODO(jpoole): Once v17 has been cut, we can update the python plugin to use it and cut a named release
    revision = "d500dd9f477bb54f8b266fae9dd35d721bebee9e",
)
