plugin_repo(
    name = "go",
    plugin = "go-rules",
    owner = "tatskaari",
    revision = "24353ec965a8f9936167dbc90f9ca519ae6ca28e", #rule-gen
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.1.1",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    revision = "v1.2.4",
)
