plugin_repo(
    name = "go",
    plugin = "go-rules",
    revision = "v1.0.0",
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)

plugin_repo(
    name = "java",
    plugin = "java-rules",
    revision = "v0.2.4",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.1.1",
)
