go_library(
    name = "cache",
    srcs = ["cache_client.go"],
    deps = [
        "///third_party/go/github.com_bazelbuild_remote-apis-sdks//go/pkg/client",
        "///third_party/go/github.com_bazelbuild_remote-apis-sdks//go/pkg/digest",
        "//src/remote/fs",
        "//src/cli/logging",
    ],
    visibility = ["//src/remote:all"],
)
