go_library(
    name = 'watch',
    srcs = ['watch.go'],
    visibility = ['PUBLIC'],
    deps = [
        '//src/core',
        '//third_party/go:fsnotify',
        '//third_party/go:logging',
        '//third_party/go:osext',
    ],
)
