go_library(
    name = 'watch',
    srcs = ['watch.go'],
    deps = [
        '//src/core',
        '//third_party/go:concurrent-map',
        '//third_party/go:fsnotify',
        '//third_party/go:logging',
    ],
    visibility = ['PUBLIC'],
)
