filegroup(
    name = "build_defs",
    srcs = ["docs.build_defs"],
    visibility = ["//docs/..."],
)

filegroup(
    name = "codelab_template",
    srcs = ["codelab_template.html"],
    visibility = ["//docs/..."],
)
