subinclude("//test/export:export_e2e_test_build_def")

# Test native target with go third_party dependency.
please_export_e2e_test(
    name = "export_native_target_with_go_dep",
    export_targets = ["//:genrule_go_dep"],
)
