java_binary(
    name = 'junit_runner',
    main_class = 'build.please.test.TestMain',
    deps = [
        '//tools/junit_runner/src/build/please/test:junit_runner',
    ],
    visibility = ['PUBLIC'],
)
