package(
    python = {
        "test_runner": "test.python_rules.custom_runner.runner.run",
        "testrunner_deps": "//test/python_rules/custom_runner:runner",
    },
)

python_test(
    name = "custom_runner_test",
    srcs = ["custom_runner_test.py"],
)
