grpc_library(
    name = "rpc_cache",
    srcs = [
        "rpc_cache.proto",
        "rpc_server.proto",
    ],
    languages = ["go"],
    visibility = [
        "//src/cache/...",
        "//tools/cache/...",
    ],
)
