go_binary(
    name = "grammar_templater",
    srcs = ["template_grammar.go"],
    visibility = ["//docs/..."],
    deps = [
        "///third_party/go/github.com_peterebden_go-cli-init_v5//flags",
    ],
)
