python_binary(
    name = "gen_parse_tree",
    main = "gen_parse_tree.py",
    deps = [
        "//third_party/python:absl",
        "//third_party/python:progress",
    ],
)

python_binary(
    name = "parse_perf_test",
    main = "parse_perf_test.py",
    deps = [
        "//third_party/python:absl",
        "//third_party/python:colorlog",
    ],
)
