go_binary(
    name = "config_templater",
    srcs = ["template_config.go"],
    visibility = ["//docs/..."],
    deps = [
        "///third_party/go/github.com_peterebden_go-cli-init_v5//flags",
        "//src/core",
    ],
)
