package core

import (
	"fmt"
	"slices"
	"sync"
)

// BuildStatement represents the start and end byte positions of a parsed statement in a BUILD file.
type BuildStatement struct {
	Start, End int
}

// Len returns the byte length of the build statement.
func (bs *BuildStatement) Len() int64 {
	return int64(bs.End - bs.Start)
}

// StartPos returns the starting byte position of the build statement.
func (bs *BuildStatement) StartPos() int64 {
	return int64(bs.Start)
}

// BuildStatements is a slice of BuildStatement that implements sort.Interface.
type BuildStatements []BuildStatement

func (s BuildStatements) Len() int           { return len(s) }
func (s BuildStatements) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }
func (s BuildStatements) Less(i, j int) bool { return s[i].StartPos() < s[j].StartPos() }

// BuildStatementProvider defines a closure that generates new build statements.
// It is used as an argument in PackageMetadata methods to defer evaluation, avoiding
// unnecessary computation when using the no-op implementation.
type BuildStatementProvider func() BuildStatement

// SubincludesLabelProvider defines a closure that generates labels for a subinclude statement.
// It is used as an argument in PackageMetadata methods to defer evaluation, avoiding
// unnecessary computation when using the no-op implementation.
type SubincludesLabelProvider func() BuildLabels

// PackageMetadata stores metadata about parsed BUILD files, mapping statements and subincludes
// to their respective targets. This supports additional logic for operations such as `plz export`
// but should be disabled for most operations by using the no-op implementation to avoid the overhead.
type PackageMetadata interface {
	// RegisterStatementTarget records that the given build target was created as a result of the
	// given statement being executed. This should only be called for statements in BUILD files.
	RegisterStatementTarget(target *BuildTarget, stmtProvider BuildStatementProvider)
	// RegisterRequiredSubinclude records that the given build target requires the given subinclude
	// labels to be built. This is used to track which subinclude statements contributed to a target's
	// definition. This should only be called for statements in BUILD files.
	RegisterRequiredSubinclude(target *BuildTarget, labelProvider SubincludesLabelProvider)
	// RegisterSubincludeStatement records that the given subinclude statement (provided by stmtProvider)
	// includes the given build label. This should only be called for statements in BUILD files.
	RegisterSubincludeStatement(label BuildLabel, stmtProvider BuildStatementProvider)
	// FindStatement returns the build statement that was responsible for generating the given target.
	// Returns an error if the target was not found in the recorded metadata.
	FindStatement(target *BuildTarget) (*BuildStatement, error)
	// FindTargets returns all build targets that were generated by the given build statement.
	// Returns an error if no targets were found for the given statement.
	FindTargets(stmt *BuildStatement) ([]*BuildTarget, error)
	// FindRequiredSubincludes returns all subinclude labels that were required by the given target.
	// Returns an error if no subinclude information was found for the target.
	FindRequiredSubincludes(target *BuildTarget) (BuildLabels, error)
	// GetSubincludedLabels returns all build labels that were included by the given subinclude statement.
	// Returns the labels and true if the statement was found, or nil and false otherwise.
	GetSubincludedLabels(stmt *BuildStatement) (BuildLabels, bool)
}

// packageMetadataImpl is the default implementation of the PackageMetadata interface.
// It uses in-memory maps to track the relationships between BUILD file statements,
// subincludes, and the build targets they define.
type packageMetadataImpl struct {
	// StmtToTarget maps each build statement (identified by its byte range in a BUILD file)
	// to the targets it produced. Since a single statement (like a custom target or loop)
	// can produce multiple targets, this is a one-to-many mapping.
	StmtToTarget map[BuildStatement][]*BuildTarget
	// TargetToSubinclude tracks the subinclude labels that were required for a target's
	// definition. This allows mapping a target back to the subincluded labels required for building
	// the target.
	TargetToSubinclude map[*BuildTarget]BuildLabels
	// LabelsPerSubincludeStmt maps a subinclude statement (identified by its position
	// in the BUILD file) to the labels it explicitly subincludes.
	LabelsPerSubincludeStmt map[BuildStatement]BuildLabels

	// mutex protects concurrent access to the metadata maps during the parallel
	// parsing of BUILD files.
	mutex sync.RWMutex
}

func newPackageMetadata() PackageMetadata {
	return &packageMetadataImpl{
		StmtToTarget:            map[BuildStatement][]*BuildTarget{},
		TargetToSubinclude:      map[*BuildTarget]BuildLabels{},
		LabelsPerSubincludeStmt: map[BuildStatement]BuildLabels{},
	}
}

func (m *packageMetadataImpl) RegisterStatementTarget(target *BuildTarget, stmtProvider BuildStatementProvider) {
	stmt := stmtProvider()

	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.StmtToTarget[stmt] = append(m.StmtToTarget[stmt], target)
}

func (m *packageMetadataImpl) RegisterRequiredSubinclude(target *BuildTarget, labelProvider SubincludesLabelProvider) {
	labels := labelProvider()
	if len(labels) == 0 {
		log.Debugf("Attempted to register empty subinclude labels for target %s", target.String())
		return
	}

	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.TargetToSubinclude[target] = append(m.TargetToSubinclude[target], labels...)
}

func (m *packageMetadataImpl) RegisterSubincludeStatement(label BuildLabel, stmtProvider BuildStatementProvider) {
	stmt := stmtProvider()

	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.LabelsPerSubincludeStmt[stmt] = append(m.LabelsPerSubincludeStmt[stmt], label)
}

func (m *packageMetadataImpl) FindStatement(target *BuildTarget) (*BuildStatement, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()

	for stmt, targets := range m.StmtToTarget {
		if slices.Contains(targets, target) {
			return &stmt, nil
		}
	}
	return nil, fmt.Errorf("Target %s not found in statement metadata.", target.String())
}

func (m *packageMetadataImpl) FindTargets(stmt *BuildStatement) ([]*BuildTarget, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()

	targets, ok := m.StmtToTarget[*stmt]
	if !ok {
		return nil, fmt.Errorf("Targets not found for statement %v.", stmt)
	}
	return targets, nil
}

func (m *packageMetadataImpl) FindRequiredSubincludes(target *BuildTarget) (BuildLabels, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()

	subincludes, ok := m.TargetToSubinclude[target]
	if !ok {
		return nil, fmt.Errorf("Subincludes not found for target %v.", target)
	}
	return subincludes, nil
}

func (m *packageMetadataImpl) GetSubincludedLabels(stmt *BuildStatement) (BuildLabels, bool) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()

	v, ok := m.LabelsPerSubincludeStmt[*stmt]
	return v, ok
}

// noopPackageMetadata implements the PackageMetadata interface with no-op methods. This is used to
// avoid the overhead of parsing metadata for operations that don't depend on it.
type noopPackageMetadata struct{}

func newNoopPackageMetadata() PackageMetadata {
	return &noopPackageMetadata{}
}

func (n *noopPackageMetadata) RegisterStatementTarget(target *BuildTarget, stmtProvider BuildStatementProvider) {
}
func (n *noopPackageMetadata) RegisterRequiredSubinclude(target *BuildTarget, labelProvider SubincludesLabelProvider) {
}
func (n *noopPackageMetadata) RegisterSubincludeStatement(label BuildLabel, stmtProvider BuildStatementProvider) {
}
func (n *noopPackageMetadata) FindStatement(target *BuildTarget) (*BuildStatement, error) {
	return nil, fmt.Errorf("metadata not tracked")
}
func (n *noopPackageMetadata) FindTargets(stmt *BuildStatement) ([]*BuildTarget, error) {
	return nil, fmt.Errorf("metadata not tracked")
}
func (n *noopPackageMetadata) FindRequiredSubincludes(target *BuildTarget) (BuildLabels, error) {
	return nil, fmt.Errorf("metadata not tracked")
}
func (n *noopPackageMetadata) GetSubincludedLabels(stmt *BuildStatement) (BuildLabels, bool) {
	return nil, false
}
