package core

import (
	"fmt"
	"slices"
)

// BuildStatement represents the start and end byte positions of a parsed statement in a BUILD file.
type BuildStatement struct {
	Start, End int
}

// Len returns the byte length of the build statement.
func (bs *BuildStatement) Len() int64 {
	return int64(bs.End - bs.Start)
}

// StartPos returns the starting byte position of the build statement.
func (bs *BuildStatement) StartPos() int64 {
	return int64(bs.Start)
}

// BuildStatements is a slice of BuildStatement that implements sort.Interface.
type BuildStatements []BuildStatement

func (s BuildStatements) Len() int           { return len(s) }
func (s BuildStatements) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }
func (s BuildStatements) Less(i, j int) bool { return s[i].StartPos() < s[j].StartPos() }

// BuildFileMetadata stores metadata about parsed BUILD files, mapping statements and subincludes to their respective targets.
type BuildFileMetadata struct {
	// a list of targets generated from each built statement
	StmtToTarget map[BuildStatement][]*BuildTarget
	// the subincluded label dependencies per target
	TargetToSubinclude map[*BuildTarget]BuildLabels
	// all the labels included for each subincludes statement
	LabelsPerSubincludeStmt map[BuildStatement]BuildLabels
}

func newBuildFileMetadata() *BuildFileMetadata {
	return &BuildFileMetadata{
		StmtToTarget:            map[BuildStatement][]*BuildTarget{},
		TargetToSubinclude:      map[*BuildTarget]BuildLabels{},
		LabelsPerSubincludeStmt: map[BuildStatement]BuildLabels{},
	}
}

// RegisterStatementTarget maps a build statement to a target it generated.
func (bfm *BuildFileMetadata) RegisterStatementTarget(stmt *BuildStatement, target *BuildTarget) {
	bfm.StmtToTarget[*stmt] = append(bfm.StmtToTarget[*stmt], target)
}

// RegisterRequiredSubinclude maps a target to the subincludes required to build it.
func (bfm *BuildFileMetadata) RegisterRequiredSubinclude(target *BuildTarget, subincludes BuildLabels) {
	bfm.TargetToSubinclude[target] = append(bfm.TargetToSubinclude[target], subincludes...)
}

// RegisterSubincludeStmt maps a subinclude statement to a label it includes.
func (bfm *BuildFileMetadata) RegisterSubincludeStmt(label BuildLabel, stmt *BuildStatement) {
	bfm.LabelsPerSubincludeStmt[*stmt] = append(bfm.LabelsPerSubincludeStmt[*stmt], label)
}

// FindStatement returns the build statement that generated the given target.
func (bfm *BuildFileMetadata) FindStatement(target *BuildTarget) (*BuildStatement, error) {
	for stmt, targets := range bfm.StmtToTarget {
		if slices.Contains(targets, target) {
			return &stmt, nil
		}
	}
	return nil, fmt.Errorf("Target %s not found in statement metadata.", target.String())
}

// FindTargets returns all targets generated by the given build statement.
func (bfm *BuildFileMetadata) FindTargets(stmt *BuildStatement) ([]*BuildTarget, error) {
	targets, ok := bfm.StmtToTarget[*stmt]
	if !ok {
		return nil, fmt.Errorf("Targets not found for statement %v.", stmt)
	}
	return targets, nil
}

// FindRequiredSubincludes returns all subinclude labels required by the given target.
func (bfm *BuildFileMetadata) FindRequiredSubincludes(target *BuildTarget) (BuildLabels, error) {
	subincludes, ok := bfm.TargetToSubinclude[target]
	if !ok {
		return nil, fmt.Errorf("Subincludes not found for target %v.", target)
	}
	return subincludes, nil
}

// GetSubincludedLabels returns the labels included by a given subinclude statement.
func (bfm *BuildFileMetadata) GetSubincludedLabels(stmt *BuildStatement) (BuildLabels, bool) {
	v, ok := bfm.LabelsPerSubincludeStmt[*stmt]
	return v, ok
}
