go_binary(
    name = "fusejs_list_builder",
    srcs = ["main.go"],
    visibility = ["//docs/..."],
    deps = [
        "///third_party/go/github.com_peterebden_go-cli-init_v5//flags",
        "//docs/tools/fusejs_list_builder/fusejslist",
        "//docs/tools/fusejs_list_builder/processhtml",
    ],
)
