go_library(
    name = "metrics",
    srcs = ["prometheus.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/cli/logging",
        "//src/core",
        "//third_party/go:prometheus",
        "//third_party/go:prometheus_common",
    ],
)
