go_library(
    name = "metrics",
    srcs = ["prometheus.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:logging",
        "//third_party/go:prometheus",
        "//third_party/go:prometheus_common",
    ],
)