go_library(
    name = "clean",
    srcs = glob(["*.go"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/build",
        "//src/core",
        "//src/fs",
        "//src/test",
        "//third_party/go:logging",
    ],
)
