filegroup(
    name = 'tools',
    deps = [
        '//tools/cache:http_cache_server',
        '//tools/cache:rpc_cache_server',
        '//tools/jarcat',
        '//tools/javac_worker',
        '//tools/junit_runner',
        '//tools/linter',
        '//tools/please_diff_graphs',
        '//tools/please_go_test',
        '//tools/please_maven',
        '//tools/please_pex',
    ],
)
