go_test(
    name = 'go_system_dep_test',
    srcs = ['system_dep_test.go'],
    labels = [
        'proto',
        'manual',
    ],
    deps = [
        '//test/system_deps:source_context',
    ],
)
