python_test(
    name = "local_lib_import_test",
    srcs = ["local_lib_import_test.py"],
    site = True,
)

python_test(
    name = "local_lib_no_import_test",
    srcs = ["local_lib_no_import_test.py"],
    site = False,
)
