go_binary(
    name = "lexicon_templater",
    srcs = ["template_lexicon.go"],
    visibility = ["//docs/..."],
    deps = [
        "///third_party/go/github.com_peterebden_go-cli-init_v5//flags",
        "//docs/tools/lexicon_templater/rules",
    ],
)
