name: plugin docs lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  get-latest:
    name: Check plugin docs versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run checking script
        shell: bash
        run: docs/plugins/lint_plugin_docs.sh
