name: plugin docs lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  get-latest:
    name: Check plugin docs versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get docs versions
        id: versions
        run: |
          nlines=$(grep -n '# The plugin docs linter' docs/BUILD | cut -d: -f1)
          echo "python=$(head -n $nlines docs/BUILD | grep python | cut -d\" -f4)" >> $GITHUB_OUTPUT
          echo "java=$(head -n $nlines docs/BUILD | grep java | cut -d\" -f4)" >> $GITHUB_OUTPUT
          echo "go=$(head -n $nlines docs/BUILD | grep go | cut -d\" -f4)" >> $GITHUB_OUTPUT
          echo "cc=$(head -n $nlines docs/BUILD | grep cc | cut -d\" -f4)" >> $GITHUB_OUTPUT
          echo "shell=$(head -n $nlines docs/BUILD | grep shell | cut -d\" -f4)" >> $GITHUB_OUTPUT

      - name: Check Python
        run: |
          plugin="python"
          latest=$(plugins/latest_tags.sh $plugin)
          docs=${{ steps.versions.outputs.python }}
          if [[ "$latest" == "$docs" ]]; then
            exit 0
          else
            echo "Update the $plugin plugin version in docs/BUILD to" "$latest"
            exit 1
          fi

      - name: Check Java
        run: |
          plugin="java"
          latest=$(plugins/latest_tags.sh $plugin)
          docs=${{ steps.versions.outputs.java }}
          if [[ "$latest" == "$docs" ]]; then
            exit 0
          else
            echo "Update the $plugin plugin version in docs/BUILD to" "$latest"
            exit 1
          fi

      - name: Check Go
        run: |
          plugin="go"
          latest=$(plugins/latest_tags.sh $plugin)
          docs=${{ steps.versions.outputs.go }}
          if [[ "$latest" == "$docs" ]]; then
            exit 0
          else
            echo "Update the $plugin plugin version in docs/BUILD to" "$latest"
            exit 1
          fi

      - name: Check CC
        run: |
          plugin="cc"
          latest=$(plugins/latest_tags.sh $plugin)
          docs=${{ steps.versions.outputs.cc }}
          if [[ "$latest" == "$docs" ]]; then
            exit 0
          else
            echo "Update the $plugin plugin version in docs/BUILD to" "$latest"
            exit 1
          fi

      - name: Check Shell
        run: |
          plugin="shell"
          latest=$(plugins/latest_tags.sh $plugin)
          docs=${{ steps.versions.outputs.shell }}
          if [[ "$latest" == "$docs" ]]; then
            exit 0
          else
            echo "Update the $plugin plugin version in docs/BUILD to" "$latest"
            exit 1
          fi
