subinclude("//test/export:export_e2e_test_build_def")

# Export both statements inside the inner if
please_export_e2e_test(
    name = "export_for_if_both",
    export_targets = [
        "//:a",
        "//:b",
    ],
)
