config_setting(
    name = "x86_64",
    values = {"cpu": "x86_64"},
    visibility = ["//test/config_rules/..."],
)

config_setting(
    name = "x86",
    values = {"cpu": "x86"},
    visibility = ["//test/config_rules/..."],
)

config_setting(
    name = "arm64",
    values = {"cpu": "arm64"},
    visibility = ["//test/config_rules/..."],
)
