go_binary(
    name = 'please_diff_graphs',
    srcs = ['plz_diff_graphs_main.go'],
    deps = [
        '//src/cli',
        '//third_party/go:logging',
        '//tools/please_diff_graphs/diff',
    ],
    visibility = ['PUBLIC'],
)
